name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: checkout
        run: echo "${{ steps.checkout.conclusion}}"
